more debugging failures

diff --git a/.github/workflows/PROpenedOrUpdated.yml b/.github/workflows/PROpenedOrUpdated.yml
--- a/.github/workflows/PROpenedOrUpdated.yml
+++ b/.github/workflows/PROpenedOrUpdated.yml
@@ -60,8 +60,11 @@ jobs:
       matrix:
         group: ${{ fromJSON(vars.GATETEST_LIST) }}
     runs-on: ubuntu-latest
+    outputs:
+      xresult: ${{steps.runtest.outputs.result}}
     steps:
-      - name: Run Gate Tests for ${{ matrix.group }}
+      - id: runtest
+        name: Run Gate Tests for ${{ matrix.group }}
         uses: asterisk/asterisk-ci-actions/AsteriskGateComposite@main
         with:
           test_type:         Gate
@@ -74,53 +77,57 @@ jobs:
           gatetest_group:    ${{matrix.group}}
           gatetest_commands: ${{vars.GATETEST_COMMANDS}}
 
-  AsteriskGateTestsFailed:
-    name: AsteriskGateTests
-    if: failure()
-    runs-on: ubuntu-latest
-    needs: AsteriskGate
-    steps:
-      - run: |
-          exit 1
-
-  AsteriskGateTestsPassed:
-    name: AsteriskGateTests
-    if: success()
-    runs-on: ubuntu-latest
-    needs: AsteriskGate
-    steps:
-      - run: |
-          exit 0
-
-  AsteriskGateTestsCancelled:
-    name: AsteriskGateTests
-    if: cancelled()
-    runs-on: ubuntu-latest
-    needs: AsteriskGate
-    steps:
-      - run: |
-          exit 1
-
-#  AsteriskGateTests:
+#  AsteriskGateTestsFailed:
 #    name: AsteriskGateTests
-#    if: always()
+#    if: failure()
 #    runs-on: ubuntu-latest
 #    needs: AsteriskGate
 #    steps:
-#      - name: Check test matrix status
-#        env:
-#          RESULT: ${{ needs.AsteriskGate.result }}
-#        run: |
-#          case $RESULT in
-#            success)
-#              echo "::notice::All Testsuite tests passed"
-#              exit 0
-#              ;;
-#            skipped)
-#              echo "::error::Testsuite tests were skipped because of an earlier failure"
-#              exit 1
-#              ;;
-#              *)
-#              echo "::error::One or more Testsuite tests failed"
-#              exit 1
-#          esac
+#      - run: |
+#          exit 1
+#
+#  AsteriskGateTestsPassed:
+#    name: AsteriskGateTests
+#    if: success()
+#    runs-on: ubuntu-latest
+#    needs: AsteriskGate
+#    steps:
+#      - run: |
+#          exit 0
+#
+#  AsteriskGateTestsCancelled:
+#    name: AsteriskGateTests
+#    if: cancelled()
+#    runs-on: ubuntu-latest
+#    needs: AsteriskGate
+#    steps:
+#      - run: |
+#          exit 1
+
+  AsteriskGateTests:
+    name: AsteriskGateTests
+    if: always()
+    runs-on: ubuntu-latest
+    needs: AsteriskGate
+    steps:
+      - name: Check test matrix status
+        env:
+          RESULT: ${{ needs.AsteriskGate.result }}
+        run: |
+          echo "all xresults: ${{ toJSON(needs.*.xresult) }}"
+          echo "all results: ${{ toJSON(needs.*.result) }}"
+          echo "composite result: ${{ needs.AsteriskGate.result }}"
+
+          case $RESULT in
+            success)
+              echo "::notice::All Testsuite tests passed"
+              exit 0
+              ;;
+            skipped)
+              echo "::error::Testsuite tests were skipped because of an earlier failure"
+              exit 1
+              ;;
+              *)
+              echo "::error::One or more Testsuite tests failed"
+              exit 1
+          esac
